# author: Ahmed Nour
# created on: 22/4/2021
# usage:
#   ansible-playbook download_file.yml --extra-vars "url=file_url dest=destination"
---
- name: Download file
  hosts: all
  tasks:
    - name: Download file
      get_url:
        url: "{{ url }}"
        dest: "{{ dest }}"
        mode: "554"
        force_basic_auth: no
        #username: '{{ username }}'
        #password: "{{ password }}"
        #owner:
        #group:
