# author: Ahmed Nour
# created on: 15/4/2021
# usage: 
#   ansible-playbook change_password.yml --extra-vars "uname=user_name upassword=new_password"
---
- name: Change password of user {{ uname }}
  become: yes
  hosts: all
  tasks:
          - name: Change password of the user
            user:
                   name: "{{ uname }}"
                   password: "{{ upassword | password_hash('sha512') }}"
                   update_password: always
